export const NEW_CURRENCIES = 'NEW_CURRENCIES';
export const CURRENCIES = 'CURRENCIES';
export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const ADD_CURRENCY = 'ADD_CURRENCY';

export const HANDLE_CHANGE_VALUE = 'HANDLE_CHANGE_VALUE';
export const CHANGE_VALUE = 'CHANGE_VALUE'

export const FETCH_NEW_CURRENCIES = 'FETCH_NEW_CURRENCIES';
export const FETCH_NEW_VALUE_CURRENCIES = 'FETCH_NEW_VALUE_CURRENCIES';

export const FETCH_ADD_NEW_CURRENCY = 'FETCH_ADD_NEW_CURRENCY';